server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false 

spring:
    application:
        name: service-registry
    config:
        import: "optional:configserver:http://localhost:8088"




