
server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

management:
    tracing:
        sampling:
            probability: 1.0
    info:
        env:
            enabled: true

spring:
    application:
        name: api-gateway
    config:
        import: "optional:configserver:http://localhost:8088"
    cloud:
        gateway:
                routes:
                - id: user-service
                  uri: lb://user-service
                  predicates:
                    - Path=/user/**
                  filters:
                    - name: AuthenticationFilter
                - id: account-service
                  uri: lb://account-service
                  predicates:
                    - Path=/account/**
                #   filters:
                #     - name: AuthenticationFilter
                - id: card-service
                  uri: lb://card-service
                  predicates:
                    - Path=/card/**
                #   filters:
                #     - name: AuthenticationFilter
                - id: transaction-service
                  uri: lb://transaction-service
                  predicates:
                    - Path=/transaction/**
                #   filters:
                #     - name: AuthenticationFilter
        